### ISSUE TITLE
facebook share post not work

### ISSUE THREAD

**Issue by sachindholu** [DzmVasileusky/needShareButton#2]
I have issue for facebook share post like
Sorry, something went wrong.
We're working on getting this fixed as soon as we can.

Please let me know how to solve issue.
![fbpost](https://user-images.githubusercontent.com/17490155/31213610-19f891b8-a9c5-11e7-8e88-ff7c3028cf49.PNG)

**Comment by DzmVasileusky** [comment]
Hello, check it now.
